from . import coffee_outlet
from . import crm_lead
from . import sale_order
from . import account_move
from . import account_payment
from . import sale_order_line
from . import pos_config
from . import pos_order
from . import pos_order_line
from . import pos_payment
from . import coffee_help
from . import coffee_crm_help
from . import coffee_sales_help